### ISSUE TITLE
Napaka

### ISSUE THREAD

**Issue by nikapavlic** [nikapavlic/Monochromatic-crossings-in-the-square#1]
V mapi analiza, datoteki poln_graf.R naj bi funkcija "presecisca" pregledala ali se dve daljici sekata ali ne in če se, poišče presečišče. Zdi pa se, da je nekje napaka, saj npr. pri iskanju presečišč za poln graf s 5 vozlišči vrne 0 presečišč... Če gre res za napako, prosiva za pomoč, saj je ne najdeva.

Zanima me tudi ali je mišljeno, da gledava kromatičnost samo dejanskih presečišč daljic ali je potrebno opazovati tudi vozlišča grafa?

lp

**Comment by jaanos** [comment]
Nekaj je očitno narobe pri preverjanju podvojenih presečišč. Namesto, da podvajanja preverjata s konkatenacijo koordinat, bo lažje in bolj zanesljivo, če za vsako vrstico uvedeta indeks, nato pa ohranita le tiste pare, kjer je prvi indeks manjši od drugega. To lahko naredita že v funkciji `poln_graf`:
```R
poln_graf <- function(datoteka) {
  dat <- data.frame(fromJSON(file = datoteka))                     #prebere JSON
  dat <- mutate(dat, i = 1:nrow(dat))                              #doda indekse
  graf <- merge(dat, dat, by = NULL)                               #kartezicni produkt
  colnames(graf) <- c("x1", "y1", "i", "x2", "y2", "j")            #spremeni imena
  graf <- filter(graf, i < j)
  graf <- graf %>% select(-i, -j) %>% mutate(i = 1:nrow(graf))
}
```
Potem združevanje v funkciji `presecisca` naredita enostavno tako:
```R
  pr <- merge(graf, graf, by = NULL)
  colnames(pr) <- c("x1", "y1", "x2", "y2", "i",
                    "x3", "y3", "x4", "y4", "j")
  pr <- filter(pr, i < j)
```
Za datoteko `podatki/tocke_5.json` funkcija vrne tri presečišča, kar se ujema s sliko, ki jo lahko dobita z ukazoma
```R
plot(c(graf$x1, graf$x2), c(graf$y1, graf$y2))
segments(graf$x1, graf$y1, graf$x2, graf$y2)
```
